### ISSUE TITLE
Advisory Letter

### ISSUE THREAD

**Issue by JameMaxwell** [JSorngard/hydrogen-eigenstates#1]
Hello, Johan Sörngård：

The code you wrote is very good, and I want to borrow this code from you in my program. Although I ran the code through your guidance and got the results, I am not very familiar with Fortran. I want to rewrite the code in python, so I want to ask you how you get the H and S matrix elements. For example, how do you deal with the second-order differential, and how do you deal with the Gaussian integral.

Thank you for reading, if I can get a document of your idea of writing this code, I will not be very grateful to you.

My email address:        202211034 @csu.edu.cn

**Comment by JameMaxwell** [comment]
"""
     _*_ encoding: utf-8 _*_
    @Author : JiangYi
    @Time : 2021/3/21 19:12
    @ Description:
    Solve the radial Schrödinger equation with B-spline function
"""
from scipy.interpolate import BSpline
import numpy as np
from scipy import integrate
import pandas
from scipy.linalg import eigvals
import matplotlib.pyplot as plt


# -------------- Define basic parameters  -------------- #
k = 9             # order
r_min = 0.0       # au.
r_max = 100.0
N = 100           # Number of Bspline
gamma = 5.0       # parameters of exponential B-spline function
n = N + k         # number of knotes

t = []          # knotes
b_list = []     # B-spline basis function
# ------------------------------------------ #


def generate_control_point():
    """
    Used to generate exponential B-spline control nodes
    :return: Control node list
    """
    control_points = []

    # The first k control points are r_min
    for i in range(k-1):
        t_i = r_min
        control_points.append(t_i)

    # Exponentially increasing control node
    for i in range(1, N-k+2):
        t_i = r_min + (r_max - r_min) * (np.exp(gamma * (i-1)/(N-k)) - 1)/(np.exp(gamma) - 1)
        control_points.append(t_i)

    # The last k control points are r_max
    for i in range(k-1):
        t_i = r_max
        control_points.append(t_i)

    return control_points


def generate_b_spline_base_by_t():
    """
    Generate the B-spline basis function set according to the control node
    :return: B-spline basis function set
    """
    y_list = []
    for i in range(len(t)-k+1):
        # extrapolate = False.  Indicates that there is only a value range within the defined domain
        y_i = BSpline.basis_element(t[i:i + k], extrapolate=False)
        y_list.append(y_i)
    return y_list


def h1_x(x, i, j):
    """
    The first integral function of the Hamiltonian
    :return:
    """
    # The two functions are separated below because their domains are different
    y1 = b_list[i](x)
    y2 = b_list[j].derivative(nu=2)(x)      # nu=2, second-order differential
    if np.isnan(y1) or np.isnan(y2):
        return 0
    else:
        return y1 * y2


def h2_x(x, i, j):
    """
    The second integral function of the Hamiltonian
    :return:
    """
    y1 = b_list[i](x)
    y2 = b_list[j](x)
    if np.isnan(y1) or np.isnan(y2):
        return 0
    else:
        return y1 * (-1/x) * y2


def s_x(x, i, j):
    """
    Integral function of S matrix element
    :return:
    """
    y1 = b_list[i](x)
    y2 = b_list[j](x)
    if np.isnan(y1) or np.isnan(y2):
        return 0
    else:
        return y1 * y2


def generate_h_and_s_by_b_list():
    """
    According to the Hamiltonian and the matrix element expression of the S matrix,
    create the H matrix and the S matrix
    :return:
    """
    H = np.zeros((N, N))        # H 是一个 N*N的矩阵, N是B样条函数的个数
    S = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            H[i][j] = integrate.quad(h1_x, r_min, r_max, args=(i, j))[0] * (-1/2.0) + \
                      integrate.quad(h2_x, r_min, r_max, args=(i, j))[0]
            S[i][j] = integrate.quad(s_x, r_min, r_max, args=(i, j))[0]
    return H, S


def write_csv(file_name, data):
    """
         This function is used to save data to a csv file
    """
    save = pandas.DataFrame(list(data))
    try:
        save.to_csv(file_name, header=0, index=0)
    except UnicodeEncodeError:
        print("Coding error")


def main():
    # 1 Generate control node
    global t
    t = generate_control_point()

    # 2 Generate a set of B-spline-base functions
    global b_list
    b_list = generate_b_spline_base_by_t()        # N个 B 样条基函数集合

    # 3 Generate S and H matrix elements
    h, s = generate_h_and_s_by_b_list()

    # 4 Obtain the eigenvalue and eigenvector according to the linear equation system H*c = E*S*c
    eigen_energy = eigvals(h, s)

    # 5 save data
    write_csv("S.csv", s)
    write_csv("H.csv", h)
    write_csv("energy.csv", np.real(eigen_energy))


if __name__ == "__main__":
    main()

**Comment by JSorngard** [comment]
Hello,

Of course you can use this code in your project!
I hope I understand your questions correctly:

I do the differentiation by differentiating the underlying B-splines the state is expanded in, using the formula in e.g. [https://en.wikipedia.org/wiki/B-spline#Derivative_expressions](https://en.wikipedia.org/wiki/B-spline#Derivative_expressions)
These derivatives are computed in the file [src/getdsplines.f90](https://github.com/JSorngard/hydrogen-eigenstates/blob/master/src/getdsplines.f90).

The integral is done through [Gaussian quadrature](https://en.wikipedia.org/wiki/Gaussian_quadrature). The needed weights and abscissas are computed in [src/gauleg.f](https://github.com/JSorngard/hydrogen-eigenstates/blob/master/src/gauleg.f) (not written by me, but by de Boor and detailed in the book Numerical Recipes) and then the integration is performed in the loop labelled "integration loop" in [src/eigensplines.f90](https://github.com/JSorngard/hydrogen-eigenstates/blob/master/src/eigensplines.f90).

Kind Regard

**Comment by JameMaxwell** [comment]
I am very happy to receive your reply.

Are you interested in telling me your programming ideas. In other words, what is your project flow chart?

Or, can you recommend some literature and reference books to help me understand your project

Kind Regard

**Comment by JSorngard** [comment]
Sorry for the late reply. It was a long while since I worked on this code, but the program is my solution to a homework problem in computational physics. The problem can be found at [this link](http://www.teori.atom.fysik.su.se/~lindroth/comp08/BsplineHatom.pdf). It is probably worth looking at since it contains some general guidelines on how to solve it that you may find useful.
